name: Flutter APK Build

on: 
  push:
    branches:
      - master
      - main
      - fix-app-freeze
  pull_request:
    branches:
      - master
      - main
      - fix-app-freeze

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'

      - run: flutter pub get

      - run: flutter build apk --release --target-platform=android-arm64

      - uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
